language: julia
os:
    - linux
julia:
    - 1.0
    - nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("NODAL")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
